### ISSUE TITLE
Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by andreasotto** [SamuelRiversMoore/icons-field#2]
Does not work with current kirby 3.

I tried to use like this:

```
              sidebar_content:
                type: structure
                label: Inhalt
                when:
                  sidebar: true
                fields:
                  xicon: 
                    label: Symbol
                    type: icons
                  content:
                    label: Inhalt
                    type: editor
```
